### ISSUE TITLE
超出索引范围，脚本死循环

### ISSUE THREAD

**Issue by Kwaiyu** [noBaldAaa/find-job#2]
控制台输出：

在索引 33155 处找不到工作。
职位描述信息/n：null
在索引 33156 处找不到工作。
职位描述信息/n：null
在索引 33157 处找不到工作。
职位描述信息/n：null
在索引 33158 处找不到工作。
职位描述信息/n：null
在索引 33159 处找不到工作。

可以看出BOSS网页上是根据当前索引值加载完成后，才会继续加后面的索引值：如当前在索引406，加载到420索引就不会在继续加载
![image](https://github.com/noBaldAaa/find-job/assets/28617728/0e10f680-557d-4a8c-9ce7-46563790a2a3)

当前如果到420，才会继续加载到435
![image](https://github.com/noBaldAaa/find-job/assets/28617728/36486982-e9c8-4847-be99-11b72d9379b6)

那么脚本在10秒内如果没有找到这个索引项目，并且没有找到描述信息节点并获取文字就会走到异常分支。
这个该怎么优化呢？

**Comment by laura-xst** [comment]
你是不是没改API_key，我刚才没改也是这样

**Comment by Kwaiyu** [comment]
> 你是不是没改API_key，我刚才没改也是这样

改了呀，我是投了一两家后才出现的，很奇怪

**Comment by Kwaiyu** [comment]
延长等待时间，或者加个重试当前索引项的函数可以解决了。closed

```
async function retryOperation(operation, delay, retries) {
  try {
    return await operation();
  } catch (error) {
    if (retries - 1 > 0) {
      console.log(`重试获取元素，剩余重试次数：${retries - 1}`);
      return new Promise((resolve) => setTimeout(resolve, delay))
          .then(() => retryOperation(operation, delay, retries - 1));
    } else {
      throw error;
    }
  }
}
```

**Comment by noBaldAaa** [comment]
很秀[强]
